// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/gofrs/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockVerifiedEmailChecker is an autogenerated mock type for the VerifiedEmailChecker type
type MockVerifiedEmailChecker struct {
	mock.Mock
}

type MockVerifiedEmailChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifiedEmailChecker) EXPECT() *MockVerifiedEmailChecker_Expecter {
	return &MockVerifiedEmailChecker_Expecter{mock: &_m.Mock}
}

// FindUserIDByVerifiedEmail provides a mock function with given fields: ctx, email
func (_m *MockVerifiedEmailChecker) FindUserIDByVerifiedEmail(ctx context.Context, email string) (uuid.UUID, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserIDByVerifiedEmail")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserIDByVerifiedEmail'
type MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call struct {
	*mock.Call
}

// FindUserIDByVerifiedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockVerifiedEmailChecker_Expecter) FindUserIDByVerifiedEmail(ctx interface{}, email interface{}) *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call {
	return &MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call{Call: _e.mock.On("FindUserIDByVerifiedEmail", ctx, email)}
}

func (_c *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call) Run(run func(ctx context.Context, email string)) *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call) Return(_a0 uuid.UUID, _a1 error) *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *MockVerifiedEmailChecker_FindUserIDByVerifiedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifiedEmailChecker creates a new instance of MockVerifiedEmailChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifiedEmailChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifiedEmailChecker {
	mock := &MockVerifiedEmailChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
