version: "2"
linters:
  default: standard
  disable:
    - lll
    - godot

  settings:
    errcheck:
      exclude-functions:
        - "(os.File).Close"
        - "(*os.File).Close"
        - "(io.Closer).Close"
        - "(net/http.Response).Body.Close"
        - "os.Remove"
        - "os.RemoveAll"

run:
  timeout: 5m
  tests: true
  concurrency: 10
  allow-parallel-runners: true
