name: Upload Blog Example App

on:
 push:
   branches: [main]
   paths:
     - 'examples/blog/**'

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.DO_API_KEY }}
#         app_spec_location: ./.do/app-dev.yaml
         app_name: modulus-app
