name: Upload Blog Example App

on:
 push:
   branches: [main]
   paths:
     - 'examples/blog/**'
     - '.github/workflows/blog-example.yml'

permissions:
  contents: read
  packages: write

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Golang with cache
       uses: magnetikonline/action-golang-cache@v5
       with:
         go-version-file: examples/blog/go.mod

     - run: go build -o ./bin/console  ./cmd/console/main.go
       working-directory: examples/blog

     - name: Cache dotenvx binary
       id: dotenvx-cache
       uses: actions/cache@v4
       with:
         path: examples/blog/dotenvx
         key: ${{ runner.os }}-dotenvx

     - name: Install dotenvx (if not cached)
       if: steps.dotenvx-cache.outputs.cache-hit != 'true'
       run: curl -sfS https://dotenvx.sh/install.sh?directory=. | sh
       working-directory: examples/blog

     - name: Log in to the Container registry
       uses: docker/login-action@v3.3.0
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.REGISTRY_TOKEN }}

     - name: Build and push Docker image
       id: push
       uses: docker/build-push-action@v6.5.0
       with:
         context: examples/blog/.
         push: true
         tags: ghcr.io/${{ github.repository }}:latest

     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       env:
         SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
       with:
         token: ${{ secrets.DO_API_KEY }}
#         app_spec_location: ./.do/app-dev.yaml
         app_name: modulus-app
